### ISSUE TITLE
Detect or hide event single tap when swipe

### ISSUE THREAD

**Issue by nakamuraos** [minwork/use-double-tap#13]
Hi @minwork, nice project.

I don't want trigger event singleTap when user swipe.

This demo: https://codesandbox.io/s/usedoubletap-forked-orb2f
You can see console when swipe will trigger callback singleTap

**Comment by MinworkCompany** [comment]
Hey @nakamuraos,

unfortunately I cannot reproduce that scenario.

This hook internally use only `onClick` handler so in your case swipe must somehow trigger `onClick` and I'm afraid I cannot help you with that issue from this library perspective because it is not related to the implementation details of the hook, rather to how `onClick` works in React itself.

**Comment by nakamuraos** [comment]
Hi @MinworkCompany

You can press & hold left mouse and move cursor on button, release the mouse to reproduce

**Comment by minwork** [comment]
Based on example you provided swipe is only "detected" when you release mouse / touch within the listened element.

This is how internally `onClick` handler works in React so it is expected behaviour. Maybe you could mitigate that by tampering with `onTouchStart` and `onTouchEnd` events and `preventDefault`, but I am not sure.

Anyway in my opinion it is not directly related to how `useDoubleTap` hook works and handling this case shouldn't be within the scope of its implementation.

If you feel otherwise or found any solution for this particular case please leave a comment. If not then I suggest closing this issue.

**Comment by nakamuraos** [comment]
Hi @minwork

Thank you for understand my thought. I think you need PRs rather this. I'll close this.

Thank you very much. Nice project.
